# Generated by Django 3.1.3 on 2022-01-09 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0002_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='chart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='chart.chart'),
        ),
    ]
